import { deletePlannerDatabase, openPlannerDatabase } from "../js/db.js?stage=7";
import { GoogleApiError, createGoogleCalendarService } from "../js/google-calendar.js?stage=7";
import { createRepositories } from "../js/repositories.js?stage=7";
import { createSyncEngine } from "../js/sync.js?stage=7";

const results=[];const list=document.querySelector("[data-results]");
const assert=(value,message="Проверка не пройдена")=>{if(!value)throw new Error(message)};
async function check(name,operation){try{await operation();results.push({name,passed:true})}catch(error){results.push({name,passed:false,error:error.message})}}
const task=(overrides={})=>({id:crypto.randomUUID(),title:"Локальная задача",shortDescription:"Коротко",details:"Локальное описание",date:"2026-10-05",hasTime:true,startTime:"10:00",durationMinutes:60,priority:"high",category:"work",status:"active",tags:["важно"],links:[],checklist:[{id:crypto.randomUUID(),text:"Пункт",isDone:true,order:0}],recurrence:null,...overrides});
const raw=(id,overrides={})=>({id,summary:`Событие ${id}`,description:"Описание Google",status:"confirmed",start:{dateTime:"2026-10-05T11:00:00+03:00",timeZone:"Europe/Moscow"},end:{dateTime:"2026-10-05T12:30:00+03:00",timeZone:"Europe/Moscow"},etag:`\"${id}\"`,updated:"2026-10-04T12:00:00Z",...overrides});
const authState=()=>{let token="token",cleared=0;return{getAccessToken:()=>token,clear(){token=null;cleared+=1},set(value){token=value},get cleared(){return cleared}}};
async function fixture(label,apiOverrides={},options={}){const name=`planner-stage7-${label}-${crypto.randomUUID()}`;const db=await openPlannerDatabase({name});const repositories=createRepositories(db);const auth=authState();const calls=[];const googleCalendar={
  async listEventChanges(calendar){calls.push(["list",calendar.id]);return{items:[raw(`${calendar.id}-1`)],nextSyncToken:`token-${calendar.id}`}},
  async insertTask(calendarId,value){calls.push(["insert",calendarId,value.title]);return{id:`remote-${value.id}`,etag:'"new"',updated:"2026-10-04T13:00:00Z"}},
  async updateTask(calendarId,eventId,value,etag){calls.push(["update",calendarId,eventId,etag,value.title]);return{id:eventId,etag:'"next"',updated:"2026-10-04T13:00:00Z"}},
  async deleteEvent(calendarId,eventId,etag){calls.push(["delete",calendarId,eventId,etag])},
  async getEvent(calendarId,eventId){calls.push(["get",calendarId,eventId]);return raw(eventId)},...apiOverrides};
let clock=Date.parse("2026-10-04T12:00:00Z");const delays=[];const engine=createSyncEngine({repositories,googleCalendar,googleAuth:auth,online:()=>options.online??true,now:()=>new Date(clock),sleep:async(ms)=>{delays.push(ms);clock+=ms}});return{name,db,repositories,auth,calls,engine,googleCalendar,delays,advance(ms){clock+=ms},async close(){db.close();await deletePlannerDatabase(name)}}}

await check("Полная синхронизация хранит отдельные sync token двух календарей",async()=>{const f=await fixture("full");const range={start:"2025-10-04",end:"2028-10-04",timeMin:"2025-10-04T00:00:00Z",timeMax:"2028-10-05T00:00:00Z"};await f.engine.synchronizeCalendars([{id:"a",summary:"A",selected:true},{id:"b",summary:"B",selected:true}],range);assert((await f.repositories.googleEventsCache.getAll()).length===2);assert((await f.repositories.syncState.get("a")).nextSyncToken==="token-a"&&(await f.repositories.syncState.get("b")).nextSyncToken==="token-b");await f.close()});

await check("Calendar API возвращает все страницы и конечный nextSyncToken",async()=>{const auth={getAccessToken:()=>"secret"};const urls=[];const api=createGoogleCalendarService({auth,fetchImpl:async(url)=>{urls.push(String(url));const second=new URL(url).searchParams.get("pageToken");return{ok:true,status:200,headers:{get:()=>null},json:async()=>second?{items:[raw("2")],nextSyncToken:"sync-final"}:{items:[raw("1")],nextPageToken:"page-2"}}}});const page=await api.listEventChanges({id:"c",summary:"C"},{timeMin:"2026-01-01T00:00:00Z",timeMax:"2027-01-01T00:00:00Z"});assert(page.items.length===2&&page.nextSyncToken==="sync-final"&&urls.length===2)});

await check("Инкрементальная синхронизация использует сохранённый token",async()=>{let options;const f=await fixture("incremental",{listEventChanges:async(calendar,value)=>{options=value;return{items:[raw("new")],nextSyncToken:"next"}}});await f.repositories.syncState.put({calendarId:"c",nextSyncToken:"old",rangeStart:"2025-01-01",rangeEnd:"2028-01-01",lastSyncAt:""});await f.engine.synchronizeCalendar({id:"c",summary:"C"},{start:"2026-01-01",end:"2027-01-01",timeMin:"",timeMax:""});assert(options.syncToken==="old"&&(await f.repositories.syncState.get("c")).nextSyncToken==="next");await f.close()});

await check("410 очищает только календарный кэш и запускает полную загрузку",async()=>{let count=0;const f=await fixture("gone",{listEventChanges:async(calendar,options)=>{count+=1;if(options.syncToken)throw new GoogleApiError(410,"Gone");return{items:[raw("fresh")],nextSyncToken:"fresh-token"}}});const local=await f.repositories.tasks.create(task());await f.repositories.googleEventsCache.put({cacheKey:"c:old",calendarId:"c",start:{date:"2026-01-01"},updated:""});await f.repositories.googleEventsCache.put({cacheKey:"other:keep",calendarId:"other",start:{date:"2026-01-01"},updated:""});await f.repositories.syncState.put({calendarId:"c",nextSyncToken:"expired",rangeStart:"2025-01-01",rangeEnd:"2028-01-01"});await f.engine.synchronizeCalendar({id:"c",summary:"C"},{start:"2026-01-01",end:"2027-01-01",timeMin:"min",timeMax:"max"});const cache=await f.repositories.googleEventsCache.getAll();assert(count===2&&cache.some(x=>x.cacheKey==="c:fresh")&&cache.some(x=>x.cacheKey==="other:keep")&&(await f.repositories.tasks.get(local.id)));await f.close()});

await check("Повторные изменения объекта объединяются в очереди",async()=>{const f=await fixture("merge",{}, {online:false});let local=await f.repositories.tasks.create(task({googleSync:{calendarId:"c",eventId:"e",etag:'"1"',syncStatus:"synced"}}));await f.engine.queueEntity(local,{action:"update",calendarId:"c",eventId:"e",etag:'"1"'});local=await f.repositories.tasks.update(local.id,{title:"Последняя версия"});await f.engine.queueEntity(local,{action:"update",calendarId:"c",eventId:"e",etag:'"1"'});const queue=await f.engine.getQueue();assert(queue.length===1&&queue[0].payload.title==="Последняя версия");await f.close()});

await check("Разные операции обрабатываются строго по порядку",async()=>{const f=await fixture("order");const a=await f.repositories.tasks.create(task());const b=await f.repositories.tasks.create(task());await f.engine.queueEntity(a,{action:"create",calendarId:"c"});await f.engine.queueEntity(b,{action:"create",calendarId:"c"});await f.engine.flush();assert(f.calls.filter(x=>x[0]==="insert").map(x=>x[2]).join(",")==="Локальная задача,Локальная задача"&&(await f.engine.getQueue()).length===0);await f.close()});

await check("Офлайн сохраняет очередь и не обращается к Google",async()=>{const f=await fixture("offline",{}, {online:false});const local=await f.repositories.tasks.create(task());await f.engine.queueEntity(local,{action:"create",calendarId:"c"});const result=await f.engine.flush();assert(result.pending===1&&f.calls.length===0&&(await f.repositories.tasks.get(local.id)).googleSync.syncStatus==="pendingCreate");await f.close()});

await check("Условное обновление отправляет If-Match без предварительного GET",async()=>{const requests=[];const api=createGoogleCalendarService({auth:{getAccessToken:()=>"token"},fetchImpl:async(url,options)=>{requests.push({url:String(url),options});return{ok:true,status:200,headers:{get:()=>null},json:async()=>({id:"e",etag:'"2"'})}}});await api.updateTask("c","e",task(), '"1"');assert(requests.length===1&&requests[0].options.headers["If-Match"]==='"1"'&&requests[0].options.method==="PUT")});

await check("412 делает один GET, применяет Google и сохраняет локальные поля",async()=>{let gets=0;const f=await fixture("conflict",{updateTask:async()=>{throw new GoogleApiError(412,"Conflict")},getEvent:async()=>{gets+=1;return raw("e",{summary:"Версия Google",recurrence:["RRULE:FREQ=WEEKLY;COUNT=4"]})}});const local=await f.repositories.tasks.create(task({googleSync:{calendarId:"c",eventId:"e",etag:'"old"',syncStatus:"synced"}}));await f.engine.queueEntity(local,{action:"update",calendarId:"c",eventId:"e",etag:'"old"'});await f.engine.flush();const updated=await f.repositories.tasks.get(local.id);const history=await f.repositories.conflictHistory.getAll();assert(gets===1&&updated.title==="Версия Google"&&updated.startTime==="11:00"&&updated.priority==="high"&&updated.tags[0]==="важно"&&updated.checklist[0].isDone&&history.length===1&&(await f.engine.getQueue()).length===0);await f.close()});

await check("Локальную версию конфликта можно отправить повторно с новым etag",async()=>{let mode="conflict",sentEtag=null;const f=await fixture("reapply",{updateTask:async(c,e,value,etag)=>{if(mode==="conflict")throw new GoogleApiError(412,"Conflict");sentEtag=etag;return{id:e,etag:'"done"'}},getEvent:async()=>raw("e",{summary:"Google",etag:'"remote"'})});const local=await f.repositories.tasks.create(task({googleSync:{calendarId:"c",eventId:"e",etag:'"old"',syncStatus:"synced"}}));await f.engine.queueEntity(local,{action:"update",calendarId:"c",eventId:"e",etag:'"old"'});await f.engine.flush();const conflict=(await f.repositories.conflictHistory.getAll())[0];mode="success";await f.engine.reapplyConflict(conflict.id);assert(sentEtag==='"remote"'&&(await f.repositories.tasks.get(local.id)).title==="Локальная задача");await f.close()});

await check("401 очищает токен и оставляет операцию до повторного входа",async()=>{const f=await fixture("unauthorized",{insertTask:async()=>{throw new GoogleApiError(401,"Unauthorized")}});const local=await f.repositories.tasks.create(task());await f.engine.queueEntity(local,{action:"create",calendarId:"c"});const result=await f.engine.flush();const queue=await f.engine.getQueue();assert(f.auth.cleared===1&&result.pending===1&&queue[0].status==="waitingAuth");await f.close()});

await check("403 без права записи становится ошибкой без потери задачи",async()=>{const f=await fixture("forbidden",{insertTask:async()=>{throw new GoogleApiError(403,"Forbidden",{error:{errors:[{reason:"forbidden"}]}})}});const local=await f.repositories.tasks.create(task());await f.engine.queueEntity(local,{action:"create",calendarId:"c"});await f.engine.flush();assert((await f.engine.getQueue())[0].status==="error"&&(await f.repositories.tasks.get(local.id)).title==="Локальная задача");await f.close()});

await check("404 завершает связь, но сохраняет локальную задачу",async()=>{const f=await fixture("notfound",{updateTask:async()=>{throw new GoogleApiError(404,"Not found")}});const local=await f.repositories.tasks.create(task({googleSync:{calendarId:"c",eventId:"missing",etag:'"1"',syncStatus:"synced"}}));await f.engine.queueEntity(local,{action:"update",calendarId:"c",eventId:"missing",etag:'"1"'});await f.engine.flush();const kept=await f.repositories.tasks.get(local.id);assert(kept.title==="Локальная задача"&&kept.googleSync.syncStatus==="readOnlyRemote"&&kept.googleSync.endedAt&&(await f.engine.getQueue()).length===0);await f.close()});

await check("429 учитывает Retry-After и прекращает автопопытки после трёх ошибок",async()=>{const f=await fixture("rate",{insertTask:async()=>{const error=new GoogleApiError(429,"Rate limit");error.retryAfterMs=4000;throw error}});const local=await f.repositories.tasks.create(task());const delays=[];f.engine.subscribe(event=>{if(event.type==="retry")delays.push(event.delay)});await f.engine.queueEntity(local,{action:"create",calendarId:"c"});await f.engine.flush({waitForDelays:true});const queue=await f.engine.getQueue();assert(delays.join(",")==="4000,4000"&&queue[0].attempts===3&&queue[0].status==="error");await f.close()});

await check("5xx использует экспоненциальные интервалы",async()=>{const f=await fixture("server",{insertTask:async()=>{throw new GoogleApiError(503,"Temporary")}});const local=await f.repositories.tasks.create(task());const delays=[];f.engine.subscribe(event=>{if(event.type==="retry")delays.push(event.delay)});await f.engine.queueEntity(local,{action:"create",calendarId:"c"});await f.engine.flush({waitForDelays:true});assert(delays.join(",")==="1000,2000");await f.close()});

await check("Без токена фоновая обработка не открывает окно и сохраняет очередь",async()=>{const f=await fixture("expired");f.auth.set(null);const local=await f.repositories.tasks.create(task());await f.engine.queueEntity(local,{action:"create",calendarId:"c"});const result=await f.engine.flush();assert(result.needsAuth&&f.calls.length===0&&(await f.engine.getQueue()).length===1);await f.close()});

await check("Удалённое Google-событие отключает связь локальной задачи",async()=>{const f=await fixture("remote-delete",{listEventChanges:async()=>({items:[{id:"gone",status:"cancelled"}],nextSyncToken:"next"})});const local=await f.repositories.tasks.create(task({googleSync:{calendarId:"c",eventId:"gone",etag:'"1"',syncStatus:"synced"}}));await f.engine.synchronizeCalendar({id:"c",summary:"C"},{start:"2026-01-01",end:"2027-01-01",timeMin:"min",timeMax:"max"},{forceFull:true});const kept=await f.repositories.tasks.get(local.id);assert(kept.googleSync.endedAt&&kept.googleSync.lastErrorCode==="REMOTE_DELETED");await f.close()});

await check("Удалённое изменение обновляет общие поля связанной задачи",async()=>{const remote=raw("linked",{summary:"Название из Google",etag:'"2"'});const f=await fixture("remote-update",{listEventChanges:async()=>({items:[remote],nextSyncToken:"next"})});const local=await f.repositories.tasks.create(task({googleSync:{calendarId:"c",eventId:"linked",etag:'"1"',syncStatus:"synced"}}));await f.engine.synchronizeCalendar({id:"c",summary:"C"},{start:"2026-01-01",end:"2027-01-01",timeMin:"min",timeMax:"max"},{forceFull:true});const updated=await f.repositories.tasks.get(local.id);assert(updated.title==="Название из Google"&&updated.priority==="high"&&updated.tags[0]==="важно"&&updated.googleSync.etag==='"2"');await f.close()});

await check("История конфликтов автоматически очищается через 30 дней",async()=>{const f=await fixture("cleanup");await f.repositories.conflictHistory.put({objectId:"x",expiresAt:"2026-10-03T00:00:00Z"});await f.repositories.conflictHistory.put({objectId:"y",expiresAt:"2026-11-03T00:00:00Z"});await f.engine.cleanupConflicts();const all=await f.repositories.conflictHistory.getAll();assert(all.length===1&&all[0].objectId==="y");await f.close()});

await check("Две вкладки обнаруживаются по revision",async()=>{const f=await fixture("revision");const local=await f.repositories.tasks.create(task());await f.repositories.tasks.update(local.id,{title:"Другая вкладка"},{expectedRevision:local.revision});let conflict=false;try{await f.repositories.tasks.update(local.id,{title:"Старая форма"},{expectedRevision:local.revision})}catch(error){conflict=error.name==="VersionError"}assert(conflict&&(await f.repositories.tasks.get(local.id)).title==="Другая вкладка");await f.close()});

results.forEach(result=>{const item=document.createElement("li");item.className=result.passed?"passed":"failed";item.textContent=result.passed?`Пройдено: ${result.name}`:`Ошибка: ${result.name} — ${result.error}`;list.append(item)});const passed=results.filter(item=>item.passed).length;document.querySelector("[data-summary]").textContent=`${passed} из ${results.length} проверок пройдено`;document.documentElement.dataset.testStatus=passed===results.length?"passed":"failed";window.__STAGE7_TEST_RESULTS__=results;
